(function(){
  const data=window.QB_KNOWLEDGE_LINKS;
  if(!data)return;
  const EXAM='qbExamSession';
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let timer=null;
  function examState(){try{return JSON.parse(localStorage.getItem(EXAM)||'null')}catch{return null}}
  function format(ms){const sec=Math.max(0,Math.floor(ms/1000)),m=Math.floor(sec/60),s=sec%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
  function refreshTimer(){const state=examState(),label=document.querySelector('#examTimer');if(!state||!label)return;label.textContent='考试计时模式 '+format(Date.now()-state.startedAt);}
  function toggleExam(){const state=examState();if(state){localStorage.removeItem(EXAM);document.body.classList.remove('exam-mode');clearInterval(timer);location.reload();return;}localStorage.setItem(EXAM,JSON.stringify({startedAt:Date.now()}));document.body.classList.add('exam-mode');timer=setInterval(refreshTimer,1000);refreshTimer();}
  function chain(card){const all=Object.values(data.cards).filter(x=>x.subject===card.subject).sort((a,b)=>(a.order||0)-(b.order||0));const i=all.findIndex(x=>x.id===card.id);return{prev:all[i-1],next:all[i+1]};}
  function enhanceKnowledge(){const detail=document.querySelector('.question-detail[data-question-id]'),panel=detail&&detail.querySelector('.knowledge-link-panel');if(!panel||panel.querySelector('.batch3-knowledge'))return;const link=data.links[detail.dataset.questionId],card=link&&data.cards[link.knowledgeId];if(!card)return;const c=chain(card),box=document.createElement('div');box.className='batch3-knowledge';box.innerHTML=`<h4>知识点前置链</h4><p>${c.prev?'前置：'+esc(c.prev.title):'本章起点'} → <b>${esc(card.title)}</b> → ${c.next?'下一步：'+esc(c.next.title):'本章终点'}</p>${card.images&&card.images.length?`<details><summary>课堂笔记原图</summary>${card.images.map(src=>`<img src="${esc(src)}" alt="${esc(card.title)}课堂笔记">`).join('')}</details>`:''}`;panel.querySelector('.knowledge-body').appendChild(box);}
  function publishCheck(){const required=['app.js','core.js','question-bank-data.js','knowledge-link-data.js','knowledge-links.js','word-data.js','styles.css','index.html','core-batch2.js','core-batch3.js'];const globals={questionBank:Boolean(window.BUNDLED_QUESTION_BANK),knowledge:Boolean(window.QB_KNOWLEDGE_LINKS),words:Boolean(window.WORD_MEMORY_WORDS)};const report={title:'GitHub 发布检查',checkedAt:new Date().toISOString(),requiredFiles:required,loadedGlobals:globals,questionCount:window.BUNDLED_QUESTION_BANK?.questions?.length||0,knowledgeLinkCount:Object.keys(data.links||{}).length,result:Object.values(globals).every(Boolean)?'核心数据已加载':'缺少核心数据文件'};const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='GitHub发布检查报告.json';a.click();URL.revokeObjectURL(a.href);}
  function addButtons(){if(document.querySelector('#examModeButton'))return;const host=document.querySelector('.top-actions')||document.querySelector('.topbar');if(!host)return;const exam=document.createElement('button');exam.id='examModeButton';exam.className='icon-button';exam.innerHTML='<span id="examTimer">考试计时模式</span>';exam.onclick=toggleExam;const check=document.createElement('button');check.className='icon-button';check.textContent='GitHub 发布检查';check.onclick=publishCheck;host.append(exam,check);if(examState()){document.body.classList.add('exam-mode');timer=setInterval(refreshTimer,1000);refreshTimer();}}
  new MutationObserver(()=>{addButtons();enhanceKnowledge();}).observe(document.body,{childList:true,subtree:true});addButtons();enhanceKnowledge();
})();
