(function(){
  const linkData=window.QB_KNOWLEDGE_LINKS, bank=window.BUNDLED_QUESTION_BANK;
  if(!linkData||!bank)return;
  const STORE='qbBatch2Stats',QUEUE='qbReattemptQueue';
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
  const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const questionMap=new Map(bank.questions.map(q=>[q.id,q]));
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function record(questionId,correct){const stats=read(STORE,{}),row=stats[questionId]||{correct:0,wrong:0,last:0};row[correct?'correct':'wrong']++;row.last=Date.now();stats[questionId]=row;write(STORE,stats);if(!correct)addQueue(questionId);}
  function addQueue(questionId){const queue=read(QUEUE,[]);if(!queue.some(x=>x.id===questionId))queue.push({id:questionId,due:Date.now()+86400000,reason:'错题重做'});write(QUEUE,queue);render();}
  function mastery(questionId){const row=read(STORE,{})[questionId]||{correct:0,wrong:0};const total=row.correct+row.wrong;return total?Math.round(row.correct/total*100):50;}
  function mode(subject){if(subject==='英语')return '三科独立模式 · 英语：短语、语法与选项陷阱';if(String(subject).includes('数学'))return '三科独立模式 · 高数：方法、步骤与计算错误';return '三科独立模式 · 计算机：概念、辨析与记忆点';}
  function similar(questionId){const link=linkData.links[questionId];if(!link)return[];return (linkData.reverse[link.knowledgeId]||[]).filter(id=>id!==questionId).slice(0,5).map(id=>questionMap.get(id)).filter(Boolean);}
  function render(){const detail=document.querySelector('.question-detail[data-question-id]');if(!detail||detail.querySelector('.batch2-panel'))return;const id=detail.dataset.questionId,q=questionMap.get(id);if(!q)return;const panel=document.createElement('section');panel.className='batch2-panel';const sims=similar(id);const queued=read(QUEUE,[]).some(x=>x.id===id);panel.innerHTML=`<div class="batch2-head"><b>${esc(mode(q.subject))}</b><span>掌握度 ${mastery(id)}%</span></div><div class="batch2-actions"><button data-retry>${queued?'已加入重做队列':'加入重做队列'}</button><button data-similar>同类题推荐 ${sims.length}</button></div><div class="batch2-similar" hidden>${sims.map(x=>`<button data-open="${esc(x.id)}">${esc((x.textStem||x.stem||'').slice(0,45))}</button>`).join('')||'暂无同知识点题目'}</div>`;panel.querySelector('[data-retry]').onclick=e=>{addQueue(id);e.currentTarget.textContent='已加入重做队列';};panel.querySelector('[data-similar]').onclick=()=>{const box=panel.querySelector('.batch2-similar');box.hidden=!box.hidden;};panel.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{if(typeof window.selectQuestion==='function')window.selectQuestion(b.dataset.open);});(detail.querySelector('.knowledge-link-panel')||detail.querySelector('.stem-box')).insertAdjacentElement('afterend',panel);}
  function weakPoints(){const stats=read(STORE,{}),rows={};for(const[id,row]of Object.entries(stats)){const link=linkData.links[id];if(!link)continue;const k=linkData.cards[link.knowledgeId];if(!k)continue;const r=rows[k.id]||{title:k.title,wrong:0,correct:0};r.wrong+=row.wrong;r.correct+=row.correct;rows[k.id]=r;}return Object.values(rows).sort((a,b)=>(b.wrong-b.correct)-(a.wrong-a.correct)).slice(0,8);}
  function addDashboard(){if(document.querySelector('#batch2Dashboard'))return;const host=document.querySelector('.top-actions')||document.querySelector('.topbar');if(!host)return;const b=document.createElement('button');b.id='batch2Dashboard';b.className='icon-button';b.textContent='薄弱知识点';b.onclick=()=>{const old=document.querySelector('.batch2-modal');if(old){old.remove();return}const list=weakPoints(),queue=read(QUEUE,[]);const box=document.createElement('div');box.className='batch2-modal';box.innerHTML=`<button class="batch2-close">关闭</button><h2>薄弱知识点</h2>${list.map((x,i)=>`<p>${i+1}. ${esc(x.title)} · 错 ${x.wrong} / 对 ${x.correct}</p>`).join('')||'<p>完成几道题后生成排名。</p>'}<h3>重做队列 ${queue.length}</h3><p>错题将在次日进入重做提醒。</p>`;document.body.appendChild(box);box.querySelector('.batch2-close').onclick=()=>box.remove();};host.appendChild(b);}
  document.addEventListener('click',e=>{const detail=document.querySelector('.question-detail[data-question-id]');if(!detail)return;if(e.target.id==='correctButton')record(detail.dataset.questionId,true);if(e.target.id==='wrongButton')record(detail.dataset.questionId,false);},true);
  new MutationObserver(()=>{render();addDashboard();}).observe(document.body,{childList:true,subtree:true});render();addDashboard();
})();
