window.SUPPLEMENTAL_WORDS = [
  { id: "blue-forest-001", term: "to", meaning: "prep. 向；到；对于；直到；为了", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-002", term: "emphasis", meaning: "n. 强调；重点；重音", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-003", term: "collective", meaning: "adj. 集体的；共同的；n. 集体；集体企业", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-004", term: "cell-phone", meaning: "n. 手机；移动电话", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-005", term: "punctual", meaning: "adj. 准时的；守时的；正点的", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-006", term: "with", meaning: "prep. 和……一起；带有；用；由于", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-007", term: "hazard", meaning: "n. 危险；危害物；偶然事件；vt. 冒……风险；冒险尝试；大胆猜测", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-008", term: "enjoy", meaning: "vt. 享受；享有；喜欢", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-009", term: "two", meaning: "num. 数字二；两个", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-010", term: "yours", meaning: "pron. 你（们）的东西；属于你（们）的", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-011", term: "dinner", meaning: "n. 正餐（通常指晚餐）；宴会", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-012", term: "dioxide", meaning: "n. 二氧化物", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-013", term: "April", meaning: "n. 四月", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-014", term: "lively", meaning: "adj. 充满活力的；活泼的；鲜艳的", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-015", term: "defy", meaning: "vt. 违抗；反抗；经受住；使不可能", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-016", term: "Internet", meaning: "n. 互联网；因特网", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-017", term: "shoulder", meaning: "n. 肩膀；肩部；路肩；vt. 承担；肩负；用肩推挤", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-018", term: "January", meaning: "n. 一月（公历第一个月份）", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-019", term: "pop", meaning: "v. 发出砰的一声；突然出现；爆裂；n. 流行音乐；砰的一声；汽水", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-020", term: "summer", meaning: "n. 夏天；夏季；全盛期；v. 过夏天；避暑", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-021", term: "sun", meaning: "n. 太阳；阳光；恒星；v. 晒太阳；使暴露于阳光下", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-022", term: "vocation", meaning: "n. 天职；职业；使命感", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-023", term: "September", meaning: "n. 九月（公历第九个月）", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-024", term: "way", meaning: "n. 方法；道路；方向；方式；程度", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-025", term: "wet", meaning: "adj. 湿的；多雨的；未干的；v. 弄湿；尿床", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-026", term: "accept", meaning: "v. 接受；同意；承认", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-027", term: "floor", meaning: "n. 地板；楼层；底部；vt. 铺地板；击倒；使震惊", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-028", term: "hall", meaning: "n. 大厅；礼堂；走廊；学生宿舍", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-029", term: "woman", meaning: "n. 成年女性；妇女", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-030", term: "aerial", meaning: "adj. 空气的；空中的；航空的；n. 天线", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-031", term: "website", meaning: "n. 网站；站点", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-032", term: "hard", meaning: "adj. 坚硬的；困难的；严厉的；努力的；adv. 努力地；猛烈地；困难地", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-033", term: "implement", meaning: "v. 实施；执行；n. 工具；器具", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-034", term: "prevent", meaning: "vt. 阻止；预防；vi. 妨碍；成为阻碍", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-035", term: "such", meaning: "det. 这样的；如此的；用于强调程度；pron. 这样的人或事物", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-036", term: "inevitable", meaning: "adj. 不可避免的；必然发生的", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-037", term: "airplane", meaning: "n. 飞机；飞行器", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-038", term: "ant", meaning: "n. 蚂蚁", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-039", term: "college", meaning: "n. 学院；大学；学会", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-040", term: "oneself", meaning: "pron. 自己；自身；亲自", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-041", term: "they", meaning: "pron. 他们／她们／它们；人们；泛指某人（单数用法）", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-042", term: "rubber", meaning: "n. 橡胶；橡皮擦；避孕套（俚语）；adj. 橡胶制的", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-043", term: "able", meaning: "adj. 有能力的；能够的；胜任的", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-044", term: "then", meaning: "adv. 那时；然后；那么；此外；adj. 当时的", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-045", term: "museum", meaning: "n. 博物馆；陈列馆", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-046", term: "in", meaning: "prep. 在……里；在……期间；以……方式；adv. 进入；在家；流行地", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-047", term: "simple", meaning: "adj. 简单的；朴素的；单纯的；n. 草药；单纯的人", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-048", term: "arrow", meaning: "n. 箭；箭头符号", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-049", term: "low", meaning: "adj. 低的；矮的；不足的；消沉的；adv. 低低地；低声地", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },
  { id: "blue-forest-050", term: "dismiss", meaning: "vt. 让……离开；解雇；驳回；不考虑；vi. 解散（军事用语）", source: "蓝色森林", tag: "蓝色森林 / 图片导入" },

  { id: "cet4-001", term: "space", meaning: "n. 空间；太空；空白处；空行；vt. 分隔开；留间隔", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-002", term: "spacious", meaning: "adj. 广阔的；宽敞的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-003", term: "spatial", meaning: "adj. 空间的；与空间有关的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-004", term: "universe", meaning: "n. 宇宙；领域；范围", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-005", term: "universal", meaning: "adj. 普遍的；全体的；共同的；n. 普遍看法；普遍特征", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-006", term: "unite", meaning: "vi.／vt. （使）团结；（使）联合", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-007", term: "unity", meaning: "n. 团结一致；统一；统一体；协调", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-008", term: "reunite", meaning: "vt.／vi. （使）团聚；（使）统一", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-009", term: "reunification", meaning: "n. 重新统一；重聚", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-010", term: "union", meaning: "n. 工会；协会；联盟；联合", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-011", term: "reunion", meaning: "n. 聚会；重聚；重逢；再联合", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-012", term: "diverse", meaning: "adj. 多样的；形形色色的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-013", term: "diversify", meaning: "vi.／vt. （使）多样化；（使）扩大经营范围", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-014", term: "diversity", meaning: "n. 多样性；各种各样的人或事", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-015", term: "convert", meaning: "vt.／vi. （使）转变；改变；使改变（信仰）；vi. 可转变为；可变化成；n. 皈依者；改变信仰的人", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-016", term: "conversion", meaning: "n. 转变；改变；（信仰的）改变", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-017", term: "convertible", meaning: "adj. 可转换的；（货币）可兑换的；n. 敞篷车；折篷汽车", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-018", term: "reverse", meaning: "vt. 逆转；扭转；撤销；推翻；使反转；vi. 倒车；n. 相反的情况；背面；倒挡；损失；adj. 相反的；反面的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-019", term: "reversal", meaning: "n. 颠倒；反转；困难；挫折", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-020", term: "reversible", meaning: "adj. 可逆的；可两面穿的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-021", term: "anniversary", meaning: "n. 周年纪念（日）", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-022", term: "annual", meaning: "adj. 一年一次的；年度的；n. 年刊；年册；一年生植物", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-023", term: "controversy", meaning: "n. 争论；争议", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-024", term: "controversial", meaning: "adj. 有争议的；引发争论的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-025", term: "contrary", meaning: "adj. 相对立的；相反的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-026", term: "contrast", meaning: "n. 差异；差别；截然不同的事物；vt. 对照；对比；vi. 截然不同；有明显差异", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-027", term: "nasty", meaning: "adj. 不友善的；糟糕的；严重的；下流的；危险的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-028", term: "astronaut", meaning: "n. 航天员；宇航员", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-029", term: "heaven", meaning: "n. 天堂；极乐之地；天空", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-030", term: "satellite", meaning: "n. 人造卫星；卫星；卫星国", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-031", term: "moon", meaning: "n. 月球；月亮；卫星", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-032", term: "develop", meaning: "vi.／vt. （使）发展；成长；患（病）；加强；vt. 开发；研制；修建；阐明；冲洗", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-033", term: "developer", meaning: "n. （房地产）开发商；开发者", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-034", term: "development", meaning: "n. 发展；进展；研发；开发", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-035", term: "developmental", meaning: "adj. 发育的；成长的；发展的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-036", term: "evolve", meaning: "vi.／vt. 进化；逐步发展", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-037", term: "evolution", meaning: "n. 进化；演变；发展", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-038", term: "evolutionary", meaning: "adj. 进化的；逐渐发展的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-039", term: "revolve", meaning: "vi. 旋转；围绕；反复思考", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-040", term: "revolution", meaning: "n. 革命；变革；旋转；旋转一周", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-041", term: "revolutionary", meaning: "adj. 革命的；革命性的；突破性的；n. 革命者；革命家", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-042", term: "involve", meaning: "vt. 需要；包含；牵涉；涉及；使参与", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-043", term: "involvement", meaning: "n. 参与；介入；投入", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-044", term: "involved", meaning: "adj. 卷入的；参与的；忙于……的；与……有恋爱关系的；复杂难懂的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-045", term: "advance", meaning: "n. 前进；进步；发展；预付款；上涨；vi.／vt. 前进；进步；发展；vt. 促进；预付；提议；提前；adj. 预先的；事先的；先行的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-046", term: "advanced", meaning: "adj. 先进的；（课程）高级的；晚期的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-047", term: "ahead", meaning: "adv. 向前面；在前面；提前；领先", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-048", term: "ongoing", meaning: "adj. 进行中的；不间断的", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-049", term: "improve", meaning: "vi.／vt. 改进；改善；提高", source: "四级", tag: "四级 / Part 1 Unit 1" },
  { id: "cet4-050", term: "improvement", meaning: "n. 改善；改进；提高", source: "四级", tag: "四级 / Part 1 Unit 1" },
];
